const componentCssVariables = {
  button: {
    filled: {
      background: '--neoverse-control-button-filled-background',
      fill: '--neoverse-control-button-filled-fill',
      hoverBackground: '--neoverse-control-button-filled-hover-background',
      hoverFill: '--neoverse-control-button-filled-hover-fill',
      shadow: '--neoverse-control-button-filled-shadow',
      hoverShadow: '--neoverse-control-button-filled-hover-shadow',
    },
    primary: {
      background: '--neoverse-control-primary-background',
      foreground: '--neoverse-control-primary-foreground',
      border: '--neoverse-control-primary-border',
      shadow: '--neoverse-control-primary-shadow',
      hoverBackground: '--neoverse-control-primary-hover-background',
      hoverShadow: '--neoverse-control-primary-hover-shadow',
      activeBackground: '--neoverse-control-primary-active-background',
    },
    secondary: {
      background: '--neoverse-control-secondary-background',
      border: '--neoverse-control-secondary-border',
      hoverBackground: '--neoverse-control-secondary-hover-background',
      shadow: '--neoverse-control-secondary-shadow',
      hoverShadow: '--neoverse-control-secondary-hover-shadow',
      foreground: '--neoverse-control-secondary-foreground',
      hoverForeground: '--neoverse-control-secondary-hover-foreground',
      activeForeground: '--neoverse-control-secondary-active-foreground',
      filter: '--neoverse-control-secondary-filter',
    },
    ghost: {
      border: '--neoverse-control-ghost-border',
      background: '--neoverse-control-ghost-background',
      foreground: '--neoverse-control-ghost-foreground',
      hoverForeground: '--neoverse-control-ghost-hover-foreground',
      activeForeground: '--neoverse-control-ghost-active-foreground',
    },
    border: '--neoverse-control-button-border',
    edge: '--neoverse-control-button-edge',
    edgeHover: '--neoverse-control-button-edge-hover',
    edgeActive: '--neoverse-control-button-edge-active',
    edgeCarrier: '--neoverse-control-button-edge-carrier',
    filter: '--neoverse-control-button-filter',
    refractionGradient: '--neoverse-control-button-refraction-gradient',
    pressGlow: '--neoverse-control-button-press-glow',
    edgeRefractionOpacity: '--neoverse-control-button-edge-refraction-opacity',
    hoverBackground: '--neoverse-control-button-hover-background',
    activeBackground: '--neoverse-control-button-active-background',
    ghostActiveBackground: '--neoverse-control-button-ghost-active-background',
    disabledOpacity: '--neoverse-control-button-disabled-opacity',
    hoverGlowOpacity: '--neoverse-control-button-hover-glow-opacity',
  },
  action: {
    gap: '--neoverse-action-gap',
    height: {
      sm: '--neoverse-action-height-sm',
      md: '--neoverse-action-height-md',
      lg: '--neoverse-action-height-lg',
    },
    paddingInline: {
      sm: '--neoverse-action-padding-inline-sm',
      md: '--neoverse-action-padding-inline-md',
      lg: '--neoverse-action-padding-inline-lg',
    },
    fontSize: {
      sm: '--neoverse-action-font-size-sm',
      md: '--neoverse-action-font-size-md',
      lg: '--neoverse-action-font-size-lg',
    },
    iconSize: {
      sm: '--neoverse-action-icon-size-sm',
      md: '--neoverse-action-icon-size-md',
      lg: '--neoverse-action-icon-size-lg',
    },
  },
  navigationItem: {
    activeBackground: '--neoverse-navigation-item-active-background',
    activeFill: '--neoverse-navigation-item-active-fill',
    activeBorder: '--neoverse-navigation-item-active-border',
    activeForeground: '--neoverse-navigation-item-active-foreground',
    activeShadow: '--neoverse-navigation-item-active-shadow',
    gap: '--neoverse-navigation-item-gap',
    compactGap: '--neoverse-navigation-item-compact-gap',
    height: {
      sm: '--neoverse-navigation-item-height-sm',
      md: '--neoverse-navigation-item-height-md',
      lg: '--neoverse-navigation-item-height-lg',
    },
    fontSize: {
      sm: '--neoverse-navigation-item-font-size-sm',
      md: '--neoverse-navigation-item-font-size-md',
      lg: '--neoverse-navigation-item-font-size-lg',
    },
    iconSize: '--neoverse-navigation-item-icon-size',
    paddingBlock: {
      sm: '--neoverse-navigation-item-padding-block-sm',
      md: '--neoverse-navigation-item-padding-block-md',
      lg: '--neoverse-navigation-item-padding-block-lg',
    },
    paddingInline: {
      sm: '--neoverse-navigation-item-padding-inline-sm',
      md: '--neoverse-navigation-item-padding-inline-md',
      lg: '--neoverse-navigation-item-padding-inline-lg',
    },
    compactPaddingInline: '--neoverse-navigation-item-compact-padding-inline',
    compactIndicatorWidth: '--neoverse-navigation-item-compact-indicator-width',
    indicatorColor: '--neoverse-navigation-item-indicator-color',
    indicatorWidth: '--neoverse-navigation-item-indicator-width',
    indicatorHeight: '--neoverse-navigation-item-indicator-height',
    indicatorInset: '--neoverse-navigation-item-indicator-inset',
    compactIndicatorInset: '--neoverse-navigation-item-compact-indicator-inset',
  },
  breadcrumb: {
    gap: '--neoverse-breadcrumb-gap',
    itemGap: '--neoverse-breadcrumb-item-gap',
    fontSize: '--neoverse-breadcrumb-font-size',
    lineHeight: '--neoverse-breadcrumb-line-height',
    fontWeight: '--neoverse-breadcrumb-font-weight',
    linkForeground: '--neoverse-breadcrumb-link-foreground',
    linkHoverForeground: '--neoverse-breadcrumb-link-hover-foreground',
    currentForeground: '--neoverse-breadcrumb-current-foreground',
    separatorForeground: '--neoverse-breadcrumb-separator-foreground',
    separatorSize: '--neoverse-breadcrumb-separator-size',
    focusColor: '--neoverse-breadcrumb-focus-color',
    focusWidth: '--neoverse-breadcrumb-focus-width',
    focusOffset: '--neoverse-breadcrumb-focus-offset',
    focusRadius: '--neoverse-breadcrumb-focus-radius',
  },
  controlSurface: {
    gap: '--neoverse-control-surface-gap',
    itemGap: '--neoverse-control-surface-item-gap',
    groupHeight: '--neoverse-control-surface-group-height',
    controlHeight: '--neoverse-control-surface-control-height',
    navigationHeight: '--neoverse-control-surface-navigation-height',
    segmentedHeight: '--neoverse-control-surface-segmented-height',
    padding: '--neoverse-control-surface-padding',
    paddingBlock: '--neoverse-control-surface-padding-block',
    paddingInline: '--neoverse-control-surface-padding-inline',
    navigationEdgeInset: '--neoverse-control-surface-navigation-edge-inset',
    dividerHeight: '--neoverse-control-surface-divider-height',
    dividerGap: '--neoverse-control-surface-divider-gap',
    dividerColor: '--neoverse-control-surface-divider-color',
    indicatorDuration: '--neoverse-control-surface-indicator-duration',
    indicatorEasing: '--neoverse-control-surface-indicator-easing',
    chromeEdgeRefractionWidth: '--neoverse-control-chrome-edge-refraction-width',
    chromeEdgeRefractionSoftness: '--neoverse-control-chrome-edge-refraction-softness',
    chromeEdgeFilter: '--neoverse-control-chrome-edge-filter',
    chromeRefractionGradient: '--neoverse-control-chrome-refraction-gradient',
    chromeEdgeRefractionOpacity: '--neoverse-control-chrome-edge-refraction-opacity',
    chromeEdgeHighlight: '--neoverse-control-chrome-edge-highlight',
    chromeTrailingPadding: '--neoverse-control-chrome-trailing-padding',
    chromeTrailingPaddingInline: '--neoverse-control-chrome-trailing-padding-inline',
  },
  statusIndicator: {
    gap: {
      sm: '--neoverse-status-indicator-gap-sm',
      md: '--neoverse-status-indicator-gap-md',
    },
    dotSize: {
      sm: '--neoverse-status-indicator-dot-size-sm',
      md: '--neoverse-status-indicator-dot-size-md',
    },
    glowOpacity: '--neoverse-status-indicator-glow-opacity',
    pulseOpacity: '--neoverse-status-indicator-pulse-opacity',
    pulseScale: '--neoverse-status-indicator-pulse-scale',
    pulseRestOpacity: '--neoverse-status-indicator-pulse-rest-opacity',
    pulseMidOpacity: '--neoverse-status-indicator-pulse-mid-opacity',
    neutral: {
      color: '--neoverse-status-indicator-neutral-color',
      glow: '--neoverse-status-indicator-neutral-glow',
      pulseBackground: '--neoverse-status-indicator-neutral-pulse-background',
      pulseShadow: '--neoverse-status-indicator-neutral-pulse-shadow',
    },
    info: {
      color: '--neoverse-status-indicator-info-color',
      glow: '--neoverse-status-indicator-info-glow',
      pulseBackground: '--neoverse-status-indicator-info-pulse-background',
      pulseShadow: '--neoverse-status-indicator-info-pulse-shadow',
    },
    success: {
      color: '--neoverse-status-indicator-success-color',
      glow: '--neoverse-status-indicator-success-glow',
      pulseBackground: '--neoverse-status-indicator-success-pulse-background',
      pulseShadow: '--neoverse-status-indicator-success-pulse-shadow',
    },
    warning: {
      color: '--neoverse-status-indicator-warning-color',
      glow: '--neoverse-status-indicator-warning-glow',
      pulseBackground: '--neoverse-status-indicator-warning-pulse-background',
      pulseShadow: '--neoverse-status-indicator-warning-pulse-shadow',
    },
    danger: {
      color: '--neoverse-status-indicator-danger-color',
      glow: '--neoverse-status-indicator-danger-glow',
      pulseBackground: '--neoverse-status-indicator-danger-pulse-background',
      pulseShadow: '--neoverse-status-indicator-danger-pulse-shadow',
    },
  },

  segmentedControl: {
    backgroundImage: '--neoverse-control-segmented-background-image',
    backgroundColor: '--neoverse-control-segmented-background-color',
    foreground: '--neoverse-control-segmented-foreground',
    activeForeground: '--neoverse-control-segmented-active-foreground',
    inset: '--neoverse-control-segmented-inset',
    embeddedInset: '--neoverse-control-segmented-embedded-inset',
    gap: '--neoverse-control-segmented-gap',
    optionMinWidth: '--neoverse-control-segmented-option-min-width',
    embeddedOptionMinWidth: '--neoverse-control-segmented-embedded-option-min-width',
    optionMinWidthCompact: '--neoverse-control-segmented-option-min-width-compact',
    optionHeightSm: '--neoverse-control-segmented-option-height-sm',
    optionPaddingBlockSm: '--neoverse-control-segmented-option-padding-block-sm',
    optionPaddingInlineSm: '--neoverse-control-segmented-option-padding-inline-sm',
    embeddedOptionPaddingInlineSm: '--neoverse-control-segmented-embedded-option-padding-inline-sm',
    optionFontSizeSm: '--neoverse-control-segmented-option-font-size-sm',
    optionFontWeight: '--neoverse-control-segmented-option-font-weight',
    optionRadius: '--neoverse-control-segmented-option-radius',
    optionPressScale: '--neoverse-control-segmented-option-press-scale',
    disabledOpacity: '--neoverse-control-segmented-disabled-opacity',
    loadingGap: '--neoverse-control-segmented-loading-gap',
    loadingSize: '--neoverse-control-segmented-loading-size',
    border: '--neoverse-control-segmented-border',
    shadow: '--neoverse-control-segmented-shadow',
    filter: '--neoverse-control-segmented-filter',
    activeBackground: '--neoverse-control-segmented-active-background',
    activeFill: '--neoverse-control-segmented-active-fill',
    activeBorder: '--neoverse-control-segmented-active-border',
    activeShadow: '--neoverse-control-segmented-active-shadow',
    shellHoverBackgroundImage: '--neoverse-control-segmented-shell-hover-background-image',
    shellHoverBackgroundColor: '--neoverse-control-segmented-shell-hover-background-color',
    shellHoverBorder: '--neoverse-control-segmented-shell-hover-border',
    shellHoverShadow: '--neoverse-control-segmented-shell-hover-shadow',
    edgeRefractionOpacity: '--neoverse-control-segmented-edge-refraction-opacity',
    edgeDisplay: '--neoverse-control-segmented-edge-display',
    optionHoverBackground: '--neoverse-control-hover-background',
  },
  badge: {
    labelOpticalOffset: '--neoverse-badge-label-optical-offset',
    background: '--neoverse-badge-background',
    foreground: '--neoverse-badge-foreground',
    shadow: '--neoverse-badge-shadow',
    info: {
      background: '--neoverse-badge-info-background',
      shadow: '--neoverse-badge-info-shadow',
    },
    success: {
      background: '--neoverse-badge-success-background',
      shadow: '--neoverse-badge-success-shadow',
    },
    warning: {
      background: '--neoverse-badge-warning-background',
      shadow: '--neoverse-badge-warning-shadow',
    },
    danger: {
      background: '--neoverse-badge-danger-background',
      shadow: '--neoverse-badge-danger-shadow',
    },
  },
  notice: {
    radius: '--neoverse-notice-radius',
    gap: '--neoverse-notice-gap',
    paddingBlock: '--neoverse-notice-padding-block',
    paddingInline: '--neoverse-notice-padding-inline',
    fontSize: '--neoverse-notice-font-size',
    foreground: '--neoverse-notice-foreground',
    neutral: {
      background: '--neoverse-notice-neutral-background',
      shadow: '--neoverse-notice-neutral-shadow',
    },
    info: {
      background: '--neoverse-notice-info-background',
      shadow: '--neoverse-notice-info-shadow',
    },
    success: {
      background: '--neoverse-notice-success-background',
      shadow: '--neoverse-notice-success-shadow',
    },
    warning: {
      background: '--neoverse-notice-warning-background',
      shadow: '--neoverse-notice-warning-shadow',
    },
    danger: {
      background: '--neoverse-notice-danger-background',
      shadow: '--neoverse-notice-danger-shadow',
    },
  },
  tooltip: {
    radius: '--neoverse-tooltip-radius',
    paddingBlock: '--neoverse-tooltip-padding-block',
    paddingInline: '--neoverse-tooltip-padding-inline',
    fontSize: '--neoverse-tooltip-font-size',
    fontWeight: '--neoverse-tooltip-font-weight',
    lineHeight: '--neoverse-tooltip-line-height',
    foreground: '--neoverse-tooltip-foreground',
    arrowSize: '--neoverse-tooltip-arrow-size',
    arrowOffset: '--neoverse-tooltip-arrow-offset',
    arrowBackground: '--neoverse-tooltip-arrow-background',
    arrowShadow: '--neoverse-tooltip-arrow-shadow',
    accentTint: '--neoverse-tooltip-accent-tint',
  },
  skeleton: {
    fill: '--neoverse-skeleton-fill',
    highlight: '--neoverse-skeleton-highlight',
    edge: '--neoverse-skeleton-edge',
    textMinHeight: '--neoverse-skeleton-text-min-height',
    titleMinHeight: '--neoverse-skeleton-title-min-height',
    shimmerDuration: '--neoverse-skeleton-shimmer-duration',
    shimmerEasing: '--neoverse-skeleton-shimmer-easing',
    pulseMidOpacity: '--neoverse-skeleton-pulse-mid-opacity',
  },
  scrollbar: {
    immersive: {
      size: '--neoverse-scrollbar-immersive-size',
      trackBorderWidth: '--neoverse-scrollbar-immersive-track-border-width',
      thumbMinLength: '--neoverse-scrollbar-immersive-thumb-min-length',
      thumbBorderWidth: '--neoverse-scrollbar-immersive-thumb-border-width',
      track: '--neoverse-scrollbar-immersive-track',
      thumb: '--neoverse-scrollbar-immersive-thumb',
      thumbHover: '--neoverse-scrollbar-immersive-thumb-hover',
      thumbActive: '--neoverse-scrollbar-immersive-thumb-active',
      thumbBackground: '--neoverse-scrollbar-immersive-thumb-background',
      thumbHoverBackground: '--neoverse-scrollbar-immersive-thumb-hover-background',
      thumbActiveBackground: '--neoverse-scrollbar-immersive-thumb-active-background',
      thumbEdge: '--neoverse-scrollbar-immersive-thumb-edge',
      thumbGlow: '--neoverse-scrollbar-immersive-thumb-glow',
    },
    overlay: {
      insetBlock: '--neoverse-scrollbar-overlay-inset-block',
      insetInline: '--neoverse-scrollbar-overlay-inset-inline',
      thumbWidth: '--neoverse-scrollbar-overlay-thumb-width',
      thumbWidthHover: '--neoverse-scrollbar-overlay-thumb-width-hover',
      thumbHoverShadow: '--neoverse-scrollbar-overlay-thumb-hover-shadow',
    },
  },
  table: {
    radius: '--neoverse-table-radius',
    cellPaddingBlock: '--neoverse-table-cell-padding-block',
    cellPaddingInline: '--neoverse-table-cell-padding-inline',
    captionGap: '--neoverse-table-caption-gap',
    fontSize: '--neoverse-table-font-size',
    lineHeight: '--neoverse-table-line-height',
    foreground: '--neoverse-table-foreground',
    hoverForeground: '--neoverse-table-hover-foreground',
    headerForeground: '--neoverse-table-header-foreground',
    captionForeground: '--neoverse-table-caption-foreground',
    background: '--neoverse-table-background',
    headerBackground: '--neoverse-table-header-background',
    stripeBackground: '--neoverse-table-stripe-background',
    hoverBackground: '--neoverse-table-hover-background',
    shadow: '--neoverse-table-shadow',
    cellShadow: '--neoverse-table-cell-shadow',
    headerShadow: '--neoverse-table-header-shadow',
    hoverShadow: '--neoverse-table-hover-shadow',
    gridLine: '--neoverse-table-grid-line',
    gridLineStrong: '--neoverse-table-grid-line-strong',
    filter: '--neoverse-table-filter',
  },
  disclosure: {
    radius: '--neoverse-disclosure-radius',
    padding: '--neoverse-disclosure-padding',
    summaryMinHeight: '--neoverse-disclosure-summary-min-height',
    summaryRadius: '--neoverse-disclosure-summary-radius',
    summaryPaddingBlock: '--neoverse-disclosure-summary-padding-block',
    summaryPaddingInline: '--neoverse-disclosure-summary-padding-inline',
    summaryGap: '--neoverse-disclosure-summary-gap',
    contentGap: '--neoverse-disclosure-content-gap',
    contentPaddingInline: '--neoverse-disclosure-content-padding-inline',
    contentPaddingBlockEnd: '--neoverse-disclosure-content-padding-block-end',
    indicatorSize: '--neoverse-disclosure-indicator-size',
    indicatorStroke: '--neoverse-disclosure-indicator-stroke',
    foreground: '--neoverse-disclosure-foreground',
    activeForeground: '--neoverse-disclosure-active-foreground',
    indicatorForeground: '--neoverse-disclosure-indicator-foreground',
    activeIndicatorForeground: '--neoverse-disclosure-active-indicator-foreground',
    background: '--neoverse-disclosure-background',
    fill: '--neoverse-disclosure-fill',
    hoverFill: '--neoverse-disclosure-hover-fill',
    openFill: '--neoverse-disclosure-open-fill',
    openHoverFill: '--neoverse-disclosure-open-hover-fill',
    openSummaryBackground: '--neoverse-disclosure-open-summary-background',
    edgeRest: '--neoverse-disclosure-edge-rest',
    edgeActive: '--neoverse-disclosure-edge-active',
    shadow: '--neoverse-disclosure-shadow',
    hoverShadow: '--neoverse-disclosure-hover-shadow',
    openShadow: '--neoverse-disclosure-open-shadow',
    filter: '--neoverse-disclosure-filter',
  },
  formControl: {
    radius: '--neoverse-form-control-radius',
    minHeight: '--neoverse-form-control-min-height',
    paddingBlock: '--neoverse-form-control-padding-block',
    paddingInline: '--neoverse-form-control-padding-inline',
    gap: '--neoverse-form-control-gap',
    fontSize: '--neoverse-form-control-font-size',
    lineHeight: '--neoverse-form-control-line-height',
    foreground: '--neoverse-form-control-foreground',
    placeholder: '--neoverse-form-control-placeholder',
    disabledForeground: '--neoverse-form-control-disabled-foreground',
    background: '--neoverse-form-control-background',
    hoverBackground: '--neoverse-form-control-hover-background',
    focusBackground: '--neoverse-form-control-focus-background',
    disabledBackground: '--neoverse-form-control-disabled-background',
    shadow: '--neoverse-form-control-shadow',
    hoverShadow: '--neoverse-form-control-hover-shadow',
    focusShadow: '--neoverse-form-control-focus-shadow',
    filter: '--neoverse-form-control-filter',
    textareaMinBlockSize: '--neoverse-textarea-min-block-size',
  },
} as const;

export const cssVariables = {
  color: {
    primitive: {
      neutral: {
        50: '--neoverse-color-neutral-50',
        100: '--neoverse-color-neutral-100',
        200: '--neoverse-color-neutral-200',
        300: '--neoverse-color-neutral-300',
        400: '--neoverse-color-neutral-400',
        500: '--neoverse-color-neutral-500',
        600: '--neoverse-color-neutral-600',
        700: '--neoverse-color-neutral-700',
        800: '--neoverse-color-neutral-800',
        900: '--neoverse-color-neutral-900',
        950: '--neoverse-color-neutral-950',
      },
      blue: {
        50: '--neoverse-color-blue-50',
        100: '--neoverse-color-blue-100',
        200: '--neoverse-color-blue-200',
        300: '--neoverse-color-blue-300',
        400: '--neoverse-color-blue-400',
        500: '--neoverse-color-blue-500',
        600: '--neoverse-color-blue-600',
        700: '--neoverse-color-blue-700',
        800: '--neoverse-color-blue-800',
        900: '--neoverse-color-blue-900',
        950: '--neoverse-color-blue-950',
      },
      cyan: {
        50: '--neoverse-color-cyan-50',
        100: '--neoverse-color-cyan-100',
        200: '--neoverse-color-cyan-200',
        300: '--neoverse-color-cyan-300',
        400: '--neoverse-color-cyan-400',
        500: '--neoverse-color-cyan-500',
        600: '--neoverse-color-cyan-600',
        700: '--neoverse-color-cyan-700',
        800: '--neoverse-color-cyan-800',
        900: '--neoverse-color-cyan-900',
        950: '--neoverse-color-cyan-950',
      },
      mint: {
        50: '--neoverse-color-mint-50',
        100: '--neoverse-color-mint-100',
        200: '--neoverse-color-mint-200',
        300: '--neoverse-color-mint-300',
        400: '--neoverse-color-mint-400',
        500: '--neoverse-color-mint-500',
        600: '--neoverse-color-mint-600',
        700: '--neoverse-color-mint-700',
        800: '--neoverse-color-mint-800',
        900: '--neoverse-color-mint-900',
        950: '--neoverse-color-mint-950',
      },
      red: {
        50: '--neoverse-color-red-50',
        100: '--neoverse-color-red-100',
        200: '--neoverse-color-red-200',
        300: '--neoverse-color-red-300',
        400: '--neoverse-color-red-400',
        500: '--neoverse-color-red-500',
        600: '--neoverse-color-red-600',
        700: '--neoverse-color-red-700',
        800: '--neoverse-color-red-800',
        900: '--neoverse-color-red-900',
        950: '--neoverse-color-red-950',
      },
      amber: {
        50: '--neoverse-color-amber-50',
        100: '--neoverse-color-amber-100',
        200: '--neoverse-color-amber-200',
        300: '--neoverse-color-amber-300',
        400: '--neoverse-color-amber-400',
        500: '--neoverse-color-amber-500',
        600: '--neoverse-color-amber-600',
        700: '--neoverse-color-amber-700',
        800: '--neoverse-color-amber-800',
        900: '--neoverse-color-amber-900',
        950: '--neoverse-color-amber-950',
      },
      green: {
        50: '--neoverse-color-green-50',
        100: '--neoverse-color-green-100',
        200: '--neoverse-color-green-200',
        300: '--neoverse-color-green-300',
        400: '--neoverse-color-green-400',
        500: '--neoverse-color-green-500',
        600: '--neoverse-color-green-600',
        700: '--neoverse-color-green-700',
        800: '--neoverse-color-green-800',
        900: '--neoverse-color-green-900',
        950: '--neoverse-color-green-950',
      },
      white: '--neoverse-color-white',
      black: '--neoverse-color-black',
      transparent: '--neoverse-color-transparent',
    },
    surface: {
      canvas: '--neoverse-color-surface-canvas',
      subtle: '--neoverse-color-surface-subtle',
      raised: '--neoverse-color-surface-raised',
      glass: '--neoverse-color-surface-glass',
      overlay: '--neoverse-color-surface-overlay',
    },
    text: {
      primary: '--neoverse-color-text-primary',
      secondary: '--neoverse-color-text-secondary',
      muted: '--neoverse-color-text-muted',
      disabled: '--neoverse-color-text-disabled',
      inverse: '--neoverse-color-text-inverse',
      onAccent: '--neoverse-color-text-on-accent',
    },
    edgeLight: '--neoverse-color-edge-light',
    ambient: {
      ice: '--neoverse-color-ambient-ice',
      mint: '--neoverse-color-ambient-mint',
      violet: '--neoverse-color-ambient-violet',
    },
    border: {
      subtle: '--neoverse-color-border-subtle',
      default: '--neoverse-color-border-default',
      strong: '--neoverse-color-border-strong',
      interactive: '--neoverse-color-border-interactive',
    },
    accent: {
      primary: '--neoverse-color-accent-primary',
      primaryForeground: '--neoverse-color-accent-primary-foreground',
      secondary: '--neoverse-color-accent-secondary',
      secondaryForeground: '--neoverse-color-accent-secondary-foreground',
      tertiary: '--neoverse-color-accent-tertiary',
      tertiaryForeground: '--neoverse-color-accent-tertiary-foreground',
      soft: '--neoverse-color-accent-soft',
    },
    action: {
      primary: '--neoverse-color-action-primary',
      primaryHover: '--neoverse-color-action-primary-hover',
      primaryActive: '--neoverse-color-action-primary-active',
      primaryForeground: '--neoverse-color-action-primary-foreground',
      secondary: '--neoverse-color-action-secondary',
      secondaryHover: '--neoverse-color-action-secondary-hover',
      secondaryActive: '--neoverse-color-action-secondary-active',
      secondaryForeground: '--neoverse-color-action-secondary-foreground',
      disabled: '--neoverse-color-action-disabled',
      disabledForeground: '--neoverse-color-action-disabled-foreground',
    },
    status: {
      info: '--neoverse-color-status-info',
      infoForeground: '--neoverse-color-status-info-foreground',
      success: '--neoverse-color-status-success',
      successForeground: '--neoverse-color-status-success-foreground',
      warning: '--neoverse-color-status-warning',
      warningForeground: '--neoverse-color-status-warning-foreground',
      danger: '--neoverse-color-status-danger',
      dangerForeground: '--neoverse-color-status-danger-foreground',
    },
    focus: {
      ring: '--neoverse-color-focus-ring',
    },
    overlay: {
      scrim: '--neoverse-color-overlay-scrim',
    },
  },
  components: componentCssVariables,
  iconSize: {
    sm: '--neoverse-icon-size-sm',
    md: '--neoverse-icon-size-md',
    lg: '--neoverse-icon-size-lg',
  },
  space: {
    0: '--neoverse-space-0',
    1: '--neoverse-space-1',
    2: '--neoverse-space-2',
    3: '--neoverse-space-3',
    4: '--neoverse-space-4',
    5: '--neoverse-space-5',
    6: '--neoverse-space-6',
    7: '--neoverse-space-7',
    8: '--neoverse-space-8',
    9: '--neoverse-space-9',
    10: '--neoverse-space-10',
    11: '--neoverse-space-11',
    12: '--neoverse-space-12',
    13: '--neoverse-space-13',
    14: '--neoverse-space-14',
    15: '--neoverse-space-15',
    16: '--neoverse-space-16',
    17: '--neoverse-space-17',
    18: '--neoverse-space-18',
    19: '--neoverse-space-19',
    20: '--neoverse-space-20',
    21: '--neoverse-space-21',
    22: '--neoverse-space-22',
    23: '--neoverse-space-23',
    24: '--neoverse-space-24',
    25: '--neoverse-space-25',
    26: '--neoverse-space-26',
    27: '--neoverse-space-27',
    28: '--neoverse-space-28',
    29: '--neoverse-space-29',
    30: '--neoverse-space-30',
    31: '--neoverse-space-31',
    32: '--neoverse-space-32',
  },
  font: {
    family: {
      sans: '--neoverse-font-family-sans',
      code: '--neoverse-font-family-code',
      codeDefault: '--neoverse-font-family-code-default',
      codeMaple: '--neoverse-font-family-code-maple',
      mono: '--neoverse-font-family-mono',
    },
    size: {
      '2xs': '--neoverse-font-size-2xs',
      xs: '--neoverse-font-size-xs',
      sm: '--neoverse-font-size-sm',
      md: '--neoverse-font-size-md',
      lg: '--neoverse-font-size-lg',
      xl: '--neoverse-font-size-xl',
      '2xl': '--neoverse-font-size-2xl',
      '3xl': '--neoverse-font-size-3xl',
      '4xl': '--neoverse-font-size-4xl',
      display: '--neoverse-font-size-display',
    },
    weight: {
      regular: '--neoverse-font-weight-regular',
      medium: '--neoverse-font-weight-medium',
      semibold: '--neoverse-font-weight-semibold',
      bold: '--neoverse-font-weight-bold',
      display: '--neoverse-font-weight-display',
    },
    lineHeight: {
      tight: '--neoverse-line-height-tight',
      snug: '--neoverse-line-height-snug',
      normal: '--neoverse-line-height-normal',
      relaxed: '--neoverse-line-height-relaxed',
    },
    letterSpacing: {
      tight: '--neoverse-letter-spacing-tight',
      normal: '--neoverse-letter-spacing-normal',
      wide: '--neoverse-letter-spacing-wide',
    },
  },
  typography: {
    family: {
      display: '--neoverse-typography-display-font-family',
      title: '--neoverse-typography-title-font-family',
      body: '--neoverse-typography-body-font-family',
      label: '--neoverse-typography-label-font-family',
      caption: '--neoverse-typography-caption-font-family',
      code: '--neoverse-typography-code-font-family',
    },
    scale: {
      display: {
        lg: {
          size: '--neoverse-typography-display-lg-size',
          lineHeight: '--neoverse-typography-display-lg-line-height',
          weight: '--neoverse-typography-display-lg-weight',
          letterSpacing: '--neoverse-typography-display-lg-letter-spacing',
        },
        md: {
          size: '--neoverse-typography-display-md-size',
          lineHeight: '--neoverse-typography-display-md-line-height',
          weight: '--neoverse-typography-display-md-weight',
          letterSpacing: '--neoverse-typography-display-md-letter-spacing',
        },
      },
      title: {
        lg: {
          size: '--neoverse-typography-title-lg-size',
          lineHeight: '--neoverse-typography-title-lg-line-height',
          weight: '--neoverse-typography-title-lg-weight',
          letterSpacing: '--neoverse-typography-title-lg-letter-spacing',
        },
        md: {
          size: '--neoverse-typography-title-md-size',
          lineHeight: '--neoverse-typography-title-md-line-height',
          weight: '--neoverse-typography-title-md-weight',
          letterSpacing: '--neoverse-typography-title-md-letter-spacing',
        },
        sm: {
          size: '--neoverse-typography-title-sm-size',
          lineHeight: '--neoverse-typography-title-sm-line-height',
          weight: '--neoverse-typography-title-sm-weight',
          letterSpacing: '--neoverse-typography-title-sm-letter-spacing',
        },
      },
      body: {
        lg: {
          size: '--neoverse-typography-body-lg-size',
          lineHeight: '--neoverse-typography-body-lg-line-height',
          weight: '--neoverse-typography-body-lg-weight',
          letterSpacing: '--neoverse-typography-body-lg-letter-spacing',
        },
        md: {
          size: '--neoverse-typography-body-md-size',
          lineHeight: '--neoverse-typography-body-md-line-height',
          weight: '--neoverse-typography-body-md-weight',
          letterSpacing: '--neoverse-typography-body-md-letter-spacing',
        },
        sm: {
          size: '--neoverse-typography-body-sm-size',
          lineHeight: '--neoverse-typography-body-sm-line-height',
          weight: '--neoverse-typography-body-sm-weight',
          letterSpacing: '--neoverse-typography-body-sm-letter-spacing',
        },
      },
      label: {
        lg: {
          size: '--neoverse-typography-label-lg-size',
          lineHeight: '--neoverse-typography-label-lg-line-height',
          weight: '--neoverse-typography-label-lg-weight',
          letterSpacing: '--neoverse-typography-label-lg-letter-spacing',
        },
        md: {
          size: '--neoverse-typography-label-md-size',
          lineHeight: '--neoverse-typography-label-md-line-height',
          weight: '--neoverse-typography-label-md-weight',
          letterSpacing: '--neoverse-typography-label-md-letter-spacing',
        },
        sm: {
          size: '--neoverse-typography-label-sm-size',
          lineHeight: '--neoverse-typography-label-sm-line-height',
          weight: '--neoverse-typography-label-sm-weight',
          letterSpacing: '--neoverse-typography-label-sm-letter-spacing',
        },
      },
    },
    caption: {
      fontFamily: '--neoverse-typography-caption-font-family',
      size: '--neoverse-typography-caption-size',
      lineHeight: '--neoverse-typography-caption-line-height',
      weight: '--neoverse-typography-caption-weight',
      letterSpacing: '--neoverse-typography-caption-letter-spacing',
    },
    code: {
      fontFamily: '--neoverse-typography-code-font-family',
      size: '--neoverse-typography-code-size',
      lineHeight: '--neoverse-typography-code-line-height',
      weight: '--neoverse-typography-code-weight',
      letterSpacing: '--neoverse-typography-code-letter-spacing',
    },
  },
  radius: {
    none: '--neoverse-radius-none',
    xs: '--neoverse-radius-xs',
    sm: '--neoverse-radius-sm',
    md: '--neoverse-radius-md',
    lg: '--neoverse-radius-lg',
    xl: '--neoverse-radius-xl',
    '2xl': '--neoverse-radius-2xl',
    pill: '--neoverse-radius-pill',
    control: '--neoverse-radius-control',
    controlInner: '--neoverse-radius-control-inner',
    card: '--neoverse-radius-card',
    panel: '--neoverse-radius-panel',
  },
  shadow: {
    none: '--neoverse-shadow-none',
    xs: '--neoverse-shadow-xs',
    sm: '--neoverse-shadow-sm',
    md: '--neoverse-shadow-md',
    lg: '--neoverse-shadow-lg',
    xl: '--neoverse-shadow-xl',
    inset: '--neoverse-shadow-inset',
    control: '--neoverse-shadow-control',
    raised: '--neoverse-shadow-raised',
    card: '--neoverse-shadow-card',
    overlay: '--neoverse-shadow-overlay',
    modal: '--neoverse-shadow-modal',
  },
  border: {
    width: {
      none: '--neoverse-border-width-none',
      thin: '--neoverse-border-width-thin',
      strong: '--neoverse-border-width-strong',
    },
    style: {
      solid: '--neoverse-border-style-solid',
    },
  },
  focus: {
    ringColor: '--neoverse-color-focus-ring',
    ringWidth: '--neoverse-focus-ring-width',
    ringOffset: '--neoverse-focus-ring-offset',
    ringOffsetColor: '--neoverse-focus-ring-offset-color',
  },
  material: {
    scale: {
      transparency: {
        opaque: '--neoverse-material-transparency-opaque',
        subtle: '--neoverse-material-transparency-subtle',
        elevated: '--neoverse-material-transparency-elevated',
        immersive: '--neoverse-material-transparency-immersive',
      },
      blur: {
        none: '--neoverse-material-blur-none',
        sm: '--neoverse-material-blur-sm',
        md: '--neoverse-material-blur-md',
        lg: '--neoverse-material-blur-lg',
      },
      saturation: {
        normal: '--neoverse-material-saturation-normal',
        subtle: '--neoverse-material-saturation-subtle',
        elevated: '--neoverse-material-saturation-elevated',
        immersive: '--neoverse-material-saturation-immersive',
      },
      filter: {
        subtle: '--neoverse-material-filter-subtle',
        elevated: '--neoverse-material-filter-elevated',
        immersive: '--neoverse-material-filter-immersive',
      },
      edgeFilter: {
        subtle: '--neoverse-material-edge-filter-subtle',
        elevated: '--neoverse-material-edge-filter-elevated',
        immersive: '--neoverse-material-edge-filter-immersive',
      },
      tint: {
        subtle: '--neoverse-material-tint-subtle',
        elevated: '--neoverse-material-tint-elevated',
        immersive: '--neoverse-material-tint-immersive',
      },
      edgeHighlight: {
        none: '--neoverse-material-edge-highlight-none',
        subtle: '--neoverse-material-edge-highlight-subtle',
        elevated: '--neoverse-material-edge-highlight-elevated',
        immersive: '--neoverse-material-edge-highlight-immersive',
      },
      innerGlow: {
        subtle: '--neoverse-material-inner-glow-subtle',
        elevated: '--neoverse-material-inner-glow-elevated',
        immersive: '--neoverse-material-inner-glow-immersive',
      },
      seamGlow: {
        subtle: '--neoverse-material-seam-glow-subtle',
        elevated: '--neoverse-material-seam-glow-elevated',
        immersive: '--neoverse-material-seam-glow-immersive',
      },
      bloom: {
        subtle: '--neoverse-material-bloom-subtle',
        elevated: '--neoverse-material-bloom-elevated',
        immersive: '--neoverse-material-bloom-immersive',
      },
      edgeRefractionOpacity: {
        subtle: '--neoverse-material-edge-refraction-opacity-subtle',
        elevated: '--neoverse-material-edge-refraction-opacity-elevated',
        immersive: '--neoverse-material-edge-refraction-opacity-immersive',
      },
      edgeRefractionWidth: {
        subtle: '--neoverse-material-edge-refraction-width-subtle',
        elevated: '--neoverse-material-edge-refraction-width-elevated',
        immersive: '--neoverse-material-edge-refraction-width-immersive',
      },
      edgeRefractionSoftness: {
        subtle: '--neoverse-material-edge-refraction-softness-subtle',
        elevated: '--neoverse-material-edge-refraction-softness-elevated',
        immersive: '--neoverse-material-edge-refraction-softness-immersive',
      },
      edgeRefractionCarrier: {
        subtle: '--neoverse-material-edge-refraction-carrier-subtle',
        elevated: '--neoverse-material-edge-refraction-carrier-elevated',
        immersive: '--neoverse-material-edge-refraction-carrier-immersive',
      },
      refractionGradient: {
        none: '--neoverse-material-refraction-gradient-none',
        subtle: '--neoverse-material-refraction-gradient-subtle',
        elevated: '--neoverse-material-refraction-gradient-elevated',
        immersive: '--neoverse-material-refraction-gradient-immersive',
      },
    },
    surface: {
      inset: {
        highlight: '--neoverse-surface-inset-highlight',
        refraction: '--neoverse-surface-inset-refraction',
        denseFill: '--neoverse-surface-inset-dense-fill',
        fill: '--neoverse-surface-inset-fill',
        sheen: '--neoverse-surface-inset-sheen',
        restBackground: '--neoverse-surface-inset-rest-background',
        hoverFill: '--neoverse-surface-inset-hover-fill',
        hoverBackground: '--neoverse-surface-inset-hover-background',
        strongFill: '--neoverse-surface-inset-strong-fill',
        strongBackground: '--neoverse-surface-inset-strong-background',
        alternateFill: '--neoverse-surface-inset-alternate-fill',
        disabledFill: '--neoverse-surface-inset-disabled-fill',
        disabledBackground: '--neoverse-surface-inset-disabled-background',
        activeHighlight: '--neoverse-surface-inset-active-highlight',
        filter: '--neoverse-surface-inset-filter',
        interactiveActiveScale: '--neoverse-surface-interactive-active-scale',
      },
      solid: {
        background: '--neoverse-material-surface-solid-background',
        backgroundFallback: '--neoverse-material-surface-solid-background-fallback',
        transparency: '--neoverse-material-surface-solid-transparency',
        blur: '--neoverse-material-surface-solid-blur',
        saturation: '--neoverse-material-surface-solid-saturation',
        border: '--neoverse-material-surface-solid-border',
        borderWidth: '--neoverse-material-surface-solid-border-width',
        edgeHighlight: '--neoverse-material-surface-solid-edge-highlight',
        shadow: '--neoverse-material-surface-solid-shadow',
        refractionGradient: '--neoverse-material-surface-solid-refraction-gradient',
      },
      subtle: {
        background: '--neoverse-material-surface-subtle-background',
        backgroundFallback: '--neoverse-material-surface-subtle-background-fallback',
        transparency: '--neoverse-material-surface-subtle-transparency',
        blur: '--neoverse-material-surface-subtle-blur',
        saturation: '--neoverse-material-surface-subtle-saturation',
        border: '--neoverse-material-surface-subtle-border',
        borderWidth: '--neoverse-material-surface-subtle-border-width',
        edgeHighlight: '--neoverse-material-surface-subtle-edge-highlight',
        shadow: '--neoverse-material-surface-subtle-shadow',
        refractionGradient: '--neoverse-material-surface-subtle-refraction-gradient',
      },
      elevated: {
        background: '--neoverse-material-surface-elevated-background',
        backgroundFallback: '--neoverse-material-surface-elevated-background-fallback',
        transparency: '--neoverse-material-surface-elevated-transparency',
        blur: '--neoverse-material-surface-elevated-blur',
        saturation: '--neoverse-material-surface-elevated-saturation',
        border: '--neoverse-material-surface-elevated-border',
        borderWidth: '--neoverse-material-surface-elevated-border-width',
        edgeHighlight: '--neoverse-material-surface-elevated-edge-highlight',
        shadow: '--neoverse-material-surface-elevated-shadow',
        refractionGradient: '--neoverse-material-surface-elevated-refraction-gradient',
      },
    },
    glass: {
      subtle: {
        background: '--neoverse-material-glass-subtle-background',
        backgroundFallback: '--neoverse-material-glass-subtle-background-fallback',
        tint: '--neoverse-material-glass-subtle-tint',
        transparency: '--neoverse-material-glass-subtle-transparency',
        blur: '--neoverse-material-glass-subtle-blur',
        saturation: '--neoverse-material-glass-subtle-saturation',
        filter: '--neoverse-material-glass-subtle-filter',
        edgeFilter: '--neoverse-material-glass-subtle-edge-filter',
        border: '--neoverse-material-glass-subtle-border',
        borderWidth: '--neoverse-material-glass-subtle-border-width',
        edgeRefractionOpacity: '--neoverse-material-glass-subtle-edge-refraction-opacity',
        edgeRefractionWidth: '--neoverse-material-glass-subtle-edge-refraction-width',
        edgeRefractionSoftness: '--neoverse-material-glass-subtle-edge-refraction-softness',
        edgeRefractionCarrier: '--neoverse-material-glass-subtle-edge-refraction-carrier',
        edgeHighlight: '--neoverse-material-glass-subtle-edge-highlight',
        innerGlow: '--neoverse-material-glass-subtle-inner-glow',
        seamGlow: '--neoverse-material-glass-subtle-seam-glow',
        bloom: '--neoverse-material-glass-subtle-bloom',
        shadow: '--neoverse-material-glass-subtle-shadow',
        hoverTransparency: '--neoverse-material-glass-subtle-hover-transparency',
        hoverBorder: '--neoverse-material-glass-subtle-hover-border',
        hoverShadow: '--neoverse-material-glass-subtle-hover-shadow',
        refractionGradient: '--neoverse-material-glass-subtle-refraction-gradient',
      },
      elevated: {
        background: '--neoverse-material-glass-elevated-background',
        backgroundFallback: '--neoverse-material-glass-elevated-background-fallback',
        tint: '--neoverse-material-glass-elevated-tint',
        transparency: '--neoverse-material-glass-elevated-transparency',
        blur: '--neoverse-material-glass-elevated-blur',
        saturation: '--neoverse-material-glass-elevated-saturation',
        filter: '--neoverse-material-glass-elevated-filter',
        edgeFilter: '--neoverse-material-glass-elevated-edge-filter',
        border: '--neoverse-material-glass-elevated-border',
        borderWidth: '--neoverse-material-glass-elevated-border-width',
        edgeRefractionOpacity: '--neoverse-material-glass-elevated-edge-refraction-opacity',
        edgeRefractionWidth: '--neoverse-material-glass-elevated-edge-refraction-width',
        edgeRefractionSoftness: '--neoverse-material-glass-elevated-edge-refraction-softness',
        edgeRefractionCarrier: '--neoverse-material-glass-elevated-edge-refraction-carrier',
        edgeHighlight: '--neoverse-material-glass-elevated-edge-highlight',
        innerGlow: '--neoverse-material-glass-elevated-inner-glow',
        seamGlow: '--neoverse-material-glass-elevated-seam-glow',
        bloom: '--neoverse-material-glass-elevated-bloom',
        shadow: '--neoverse-material-glass-elevated-shadow',
        hoverTransparency: '--neoverse-material-glass-elevated-hover-transparency',
        hoverBorder: '--neoverse-material-glass-elevated-hover-border',
        hoverShadow: '--neoverse-material-glass-elevated-hover-shadow',
        refractionGradient: '--neoverse-material-glass-elevated-refraction-gradient',
      },
      immersive: {
        background: '--neoverse-material-glass-immersive-background',
        backgroundFallback: '--neoverse-material-glass-immersive-background-fallback',
        tint: '--neoverse-material-glass-immersive-tint',
        transparency: '--neoverse-material-glass-immersive-transparency',
        blur: '--neoverse-material-glass-immersive-blur',
        saturation: '--neoverse-material-glass-immersive-saturation',
        filter: '--neoverse-material-glass-immersive-filter',
        edgeFilter: '--neoverse-material-glass-immersive-edge-filter',
        border: '--neoverse-material-glass-immersive-border',
        borderWidth: '--neoverse-material-glass-immersive-border-width',
        edgeRefractionOpacity: '--neoverse-material-glass-immersive-edge-refraction-opacity',
        edgeRefractionWidth: '--neoverse-material-glass-immersive-edge-refraction-width',
        edgeRefractionSoftness: '--neoverse-material-glass-immersive-edge-refraction-softness',
        edgeRefractionCarrier: '--neoverse-material-glass-immersive-edge-refraction-carrier',
        edgeHighlight: '--neoverse-material-glass-immersive-edge-highlight',
        innerGlow: '--neoverse-material-glass-immersive-inner-glow',
        seamGlow: '--neoverse-material-glass-immersive-seam-glow',
        bloom: '--neoverse-material-glass-immersive-bloom',
        shadow: '--neoverse-material-glass-immersive-shadow',
        hoverTransparency: '--neoverse-material-glass-immersive-hover-transparency',
        hoverBorder: '--neoverse-material-glass-immersive-hover-border',
        hoverShadow: '--neoverse-material-glass-immersive-hover-shadow',
        refractionGradient: '--neoverse-material-glass-immersive-refraction-gradient',
      },
    },
  },
  motion: {
    duration: {
      fast: '--neoverse-motion-duration-fast',
      standard: '--neoverse-motion-duration-standard',
      expressive: '--neoverse-motion-duration-expressive',
    },
    easing: {
      linear: '--neoverse-motion-easing-linear',
      standard: '--neoverse-motion-easing-standard',
      emphasized: '--neoverse-motion-easing-emphasized',
    },
    spatialDistance: '--neoverse-motion-spatial-distance',
  },
  layout: {
    container: {
      sm: '--neoverse-layout-container-sm',
      md: '--neoverse-layout-container-md',
      lg: '--neoverse-layout-container-lg',
      xl: '--neoverse-layout-container-xl',
      '2xl': '--neoverse-layout-container-2xl',
    },
    gutter: {
      inline: '--neoverse-layout-gutter-inline',
      block: '--neoverse-layout-gutter-block',
    },
    page: {
      maxWidth: '--neoverse-layout-page-max-width',
      paddingInline: '--neoverse-layout-page-padding-inline',
      paddingBlock: '--neoverse-layout-page-padding-block',
    },
    contentMaxWidth: '--neoverse-layout-content-max-width',
    reading: {
      width: '--neoverse-layout-reading-width',
      wideWidth: '--neoverse-layout-reading-wide-width',
    },
    sidebar: {
      width: '--neoverse-layout-sidebar-width',
      drawerWidth: '--neoverse-layout-sidebar-drawer-width',
    },
    headerMinHeight: '--neoverse-layout-header-min-height',
    gridGap: '--neoverse-layout-grid-gap',
    presentationRootSize: '--neoverse-layout-presentation-root-size',
    layer: {
      base: '--neoverse-layout-layer-base',
      raised: '--neoverse-layout-layer-raised',
      sticky: '--neoverse-layout-layer-sticky',
      overlay: '--neoverse-layout-layer-overlay',
      modal: '--neoverse-layout-layer-modal',
      toast: '--neoverse-layout-layer-toast',
    },
  },
} as const;

export const layoutBreakpoints = {
  sm: 640,
  md: 768,
  lg: 1024,
  xl: 1280,
  '2xl': 1536,
} as const;

export type CssVariables = typeof cssVariables;
export type ColorToken = keyof CssVariables['color'];
export type ColorPrimitiveFamily = keyof CssVariables['color']['primitive'];
export type ComponentToken = keyof CssVariables['components'];
export type ButtonToken = keyof CssVariables['components']['button'];
export type ButtonVariantToken = keyof CssVariables['components']['button']['primary'];
export type ActionToken = keyof CssVariables['components']['action'];
export type NavigationItemToken = keyof CssVariables['components']['navigationItem'];
export type BreadcrumbToken = keyof CssVariables['components']['breadcrumb'];
export type ControlSurfaceToken = keyof CssVariables['components']['controlSurface'];
export type StatusIndicatorToken = keyof CssVariables['components']['statusIndicator'];
export type SegmentedControlToken = keyof CssVariables['components']['segmentedControl'];
export type BadgeToken = keyof CssVariables['components']['badge'];
export type NoticeToken = keyof CssVariables['components']['notice'];
export type TooltipToken = keyof CssVariables['components']['tooltip'];
export type SkeletonToken = keyof CssVariables['components']['skeleton'];
export type ScrollbarToken = keyof CssVariables['components']['scrollbar'];
export type ImmersiveScrollbarToken = keyof CssVariables['components']['scrollbar']['immersive'];
export type SpaceToken = keyof CssVariables['space'];
export type FontFamilyToken = keyof CssVariables['font']['family'];
export type FontSizeToken = keyof CssVariables['font']['size'];
export type FontWeightToken = keyof CssVariables['font']['weight'];
export type LineHeightToken = keyof CssVariables['font']['lineHeight'];
export type LetterSpacingToken = keyof CssVariables['font']['letterSpacing'];
export type TypographyRole = keyof CssVariables['typography'];
export type RadiusToken = keyof CssVariables['radius'];
export type ShadowToken = keyof CssVariables['shadow'];
export type FocusToken = keyof CssVariables['focus'];
export type MaterialTransparencyToken = keyof CssVariables['material']['scale']['transparency'];
export type MaterialBlurToken = keyof CssVariables['material']['scale']['blur'];
export type MaterialSaturationToken = keyof CssVariables['material']['scale']['saturation'];
export type MaterialFilterToken = keyof CssVariables['material']['scale']['filter'];
export type MaterialEdgeFilterToken = keyof CssVariables['material']['scale']['edgeFilter'];
export type MaterialTintToken = keyof CssVariables['material']['scale']['tint'];
export type MaterialEdgeHighlightToken = keyof CssVariables['material']['scale']['edgeHighlight'];
export type MaterialInnerGlowToken = keyof CssVariables['material']['scale']['innerGlow'];
export type MaterialSeamGlowToken = keyof CssVariables['material']['scale']['seamGlow'];
export type MaterialBloomToken = keyof CssVariables['material']['scale']['bloom'];
export type MaterialEdgeRefractionOpacityToken =
  keyof CssVariables['material']['scale']['edgeRefractionOpacity'];
export type MaterialEdgeRefractionWidthToken =
  keyof CssVariables['material']['scale']['edgeRefractionWidth'];
export type MaterialEdgeRefractionSoftnessToken =
  keyof CssVariables['material']['scale']['edgeRefractionSoftness'];
export type MaterialRefractionGradientToken =
  keyof CssVariables['material']['scale']['refractionGradient'];
export type MaterialSurfaceToken = keyof CssVariables['material']['surface'];
export type MaterialGlassToken = keyof CssVariables['material']['glass'];
export type MotionToken = keyof CssVariables['motion'];
export type MotionDurationToken = keyof CssVariables['motion']['duration'];
export type MotionEasingToken = keyof CssVariables['motion']['easing'];
export type BorderWidthToken = keyof CssVariables['border']['width'];
export type LayoutContainerToken = keyof CssVariables['layout']['container'];
export type LayoutBreakpoint = keyof typeof layoutBreakpoints;
