export const cssVariables = {
  color: {
    primitive: {
      neutral: {
        50: '--neoverse-color-neutral-50',
        100: '--neoverse-color-neutral-100',
        200: '--neoverse-color-neutral-200',
        300: '--neoverse-color-neutral-300',
        400: '--neoverse-color-neutral-400',
        500: '--neoverse-color-neutral-500',
        600: '--neoverse-color-neutral-600',
        700: '--neoverse-color-neutral-700',
        800: '--neoverse-color-neutral-800',
        900: '--neoverse-color-neutral-900',
        950: '--neoverse-color-neutral-950',
      },
      blue: {
        50: '--neoverse-color-blue-50',
        100: '--neoverse-color-blue-100',
        200: '--neoverse-color-blue-200',
        300: '--neoverse-color-blue-300',
        400: '--neoverse-color-blue-400',
        500: '--neoverse-color-blue-500',
        600: '--neoverse-color-blue-600',
        700: '--neoverse-color-blue-700',
        800: '--neoverse-color-blue-800',
        900: '--neoverse-color-blue-900',
        950: '--neoverse-color-blue-950',
      },
      cyan: {
        50: '--neoverse-color-cyan-50',
        100: '--neoverse-color-cyan-100',
        200: '--neoverse-color-cyan-200',
        300: '--neoverse-color-cyan-300',
        400: '--neoverse-color-cyan-400',
        500: '--neoverse-color-cyan-500',
        600: '--neoverse-color-cyan-600',
        700: '--neoverse-color-cyan-700',
        800: '--neoverse-color-cyan-800',
        900: '--neoverse-color-cyan-900',
        950: '--neoverse-color-cyan-950',
      },
      mint: {
        50: '--neoverse-color-mint-50',
        100: '--neoverse-color-mint-100',
        200: '--neoverse-color-mint-200',
        300: '--neoverse-color-mint-300',
        400: '--neoverse-color-mint-400',
        500: '--neoverse-color-mint-500',
        600: '--neoverse-color-mint-600',
        700: '--neoverse-color-mint-700',
        800: '--neoverse-color-mint-800',
        900: '--neoverse-color-mint-900',
        950: '--neoverse-color-mint-950',
      },
      red: {
        50: '--neoverse-color-red-50',
        100: '--neoverse-color-red-100',
        200: '--neoverse-color-red-200',
        300: '--neoverse-color-red-300',
        400: '--neoverse-color-red-400',
        500: '--neoverse-color-red-500',
        600: '--neoverse-color-red-600',
        700: '--neoverse-color-red-700',
        800: '--neoverse-color-red-800',
        900: '--neoverse-color-red-900',
        950: '--neoverse-color-red-950',
      },
      amber: {
        50: '--neoverse-color-amber-50',
        100: '--neoverse-color-amber-100',
        200: '--neoverse-color-amber-200',
        300: '--neoverse-color-amber-300',
        400: '--neoverse-color-amber-400',
        500: '--neoverse-color-amber-500',
        600: '--neoverse-color-amber-600',
        700: '--neoverse-color-amber-700',
        800: '--neoverse-color-amber-800',
        900: '--neoverse-color-amber-900',
        950: '--neoverse-color-amber-950',
      },
      green: {
        50: '--neoverse-color-green-50',
        100: '--neoverse-color-green-100',
        200: '--neoverse-color-green-200',
        300: '--neoverse-color-green-300',
        400: '--neoverse-color-green-400',
        500: '--neoverse-color-green-500',
        600: '--neoverse-color-green-600',
        700: '--neoverse-color-green-700',
        800: '--neoverse-color-green-800',
        900: '--neoverse-color-green-900',
        950: '--neoverse-color-green-950',
      },
      white: '--neoverse-color-white',
      black: '--neoverse-color-black',
      transparent: '--neoverse-color-transparent',
    },
    surface: {
      canvas: '--neoverse-color-surface-canvas',
      subtle: '--neoverse-color-surface-subtle',
      raised: '--neoverse-color-surface-raised',
      glass: '--neoverse-color-surface-glass',
      overlay: '--neoverse-color-surface-overlay',
    },
    text: {
      primary: '--neoverse-color-text-primary',
      secondary: '--neoverse-color-text-secondary',
      muted: '--neoverse-color-text-muted',
      disabled: '--neoverse-color-text-disabled',
      inverse: '--neoverse-color-text-inverse',
      onAccent: '--neoverse-color-text-on-accent',
    },
    edgeLight: '--neoverse-color-edge-light',
    ambient: {
      ice: '--neoverse-color-ambient-ice',
      mint: '--neoverse-color-ambient-mint',
      violet: '--neoverse-color-ambient-violet',
    },
    border: {
      subtle: '--neoverse-color-border-subtle',
      default: '--neoverse-color-border-default',
      strong: '--neoverse-color-border-strong',
      interactive: '--neoverse-color-border-interactive',
    },
    accent: {
      primary: '--neoverse-color-accent-primary',
      primaryForeground: '--neoverse-color-accent-primary-foreground',
      secondary: '--neoverse-color-accent-secondary',
      secondaryForeground: '--neoverse-color-accent-secondary-foreground',
      tertiary: '--neoverse-color-accent-tertiary',
      tertiaryForeground: '--neoverse-color-accent-tertiary-foreground',
      soft: '--neoverse-color-accent-soft',
    },
    action: {
      primary: '--neoverse-color-action-primary',
      primaryHover: '--neoverse-color-action-primary-hover',
      primaryActive: '--neoverse-color-action-primary-active',
      primaryForeground: '--neoverse-color-action-primary-foreground',
      secondary: '--neoverse-color-action-secondary',
      secondaryHover: '--neoverse-color-action-secondary-hover',
      secondaryActive: '--neoverse-color-action-secondary-active',
      secondaryForeground: '--neoverse-color-action-secondary-foreground',
      disabled: '--neoverse-color-action-disabled',
      disabledForeground: '--neoverse-color-action-disabled-foreground',
    },
    status: {
      info: '--neoverse-color-status-info',
      infoForeground: '--neoverse-color-status-info-foreground',
      success: '--neoverse-color-status-success',
      successForeground: '--neoverse-color-status-success-foreground',
      warning: '--neoverse-color-status-warning',
      warningForeground: '--neoverse-color-status-warning-foreground',
      danger: '--neoverse-color-status-danger',
      dangerForeground: '--neoverse-color-status-danger-foreground',
    },
    focus: {
      ring: '--neoverse-color-focus-ring',
    },
    overlay: {
      scrim: '--neoverse-color-overlay-scrim',
    },
  },
  control: {
    primaryBackground: '--neoverse-control-primary-background',
    primaryForeground: '--neoverse-control-primary-foreground',
    primaryBorder: '--neoverse-control-primary-border',
    primaryShadow: '--neoverse-control-primary-shadow',
    primaryHoverBackground: '--neoverse-control-primary-hover-background',
    primaryHoverShadow: '--neoverse-control-primary-hover-shadow',
    primaryActiveBackground: '--neoverse-control-primary-active-background',
    buttonEdge: '--neoverse-control-button-edge',
    buttonHoverBackground: '--neoverse-control-button-hover-background',
    buttonActiveBackground: '--neoverse-control-button-active-background',
    buttonGhostActiveBackground: '--neoverse-control-button-ghost-active-background',
    secondaryBackground: '--neoverse-control-secondary-background',
    secondaryBorder: '--neoverse-control-secondary-border',
    secondaryHoverBackground: '--neoverse-control-secondary-hover-background',
    secondaryShadow: '--neoverse-control-secondary-shadow',
    secondaryHoverShadow: '--neoverse-control-secondary-hover-shadow',
    secondaryFilter: '--neoverse-control-secondary-filter',
    segmentedBackground: '--neoverse-control-segmented-background',
    segmentedBorder: '--neoverse-control-segmented-border',
    segmentedShadow: '--neoverse-control-segmented-shadow',
    activeBackground: '--neoverse-control-active-background',
    activeBorder: '--neoverse-control-active-border',
    activeHighlight: '--neoverse-control-active-highlight',
    activeShadow: '--neoverse-control-active-shadow',
    hoverBackground: '--neoverse-control-hover-background',
  },
  scrollbar: {
    immersive: {
      size: '--neoverse-scrollbar-immersive-size',
      track: '--neoverse-scrollbar-immersive-track',
      thumb: '--neoverse-scrollbar-immersive-thumb',
      thumbHover: '--neoverse-scrollbar-immersive-thumb-hover',
      thumbActive: '--neoverse-scrollbar-immersive-thumb-active',
      thumbBackground: '--neoverse-scrollbar-immersive-thumb-background',
      thumbHoverBackground: '--neoverse-scrollbar-immersive-thumb-hover-background',
      thumbActiveBackground: '--neoverse-scrollbar-immersive-thumb-active-background',
      thumbEdge: '--neoverse-scrollbar-immersive-thumb-edge',
      thumbGlow: '--neoverse-scrollbar-immersive-thumb-glow',
    },
  },
  skeleton: {
    fill: '--neoverse-skeleton-fill',
    highlight: '--neoverse-skeleton-highlight',
    edge: '--neoverse-skeleton-edge',
    shimmerDuration: '--neoverse-skeleton-shimmer-duration',
    shimmerEasing: '--neoverse-skeleton-shimmer-easing',
  },
  space: {
    0: '--neoverse-space-0',
    1: '--neoverse-space-1',
    2: '--neoverse-space-2',
    3: '--neoverse-space-3',
    4: '--neoverse-space-4',
    5: '--neoverse-space-5',
    6: '--neoverse-space-6',
    7: '--neoverse-space-7',
    8: '--neoverse-space-8',
    9: '--neoverse-space-9',
    10: '--neoverse-space-10',
    11: '--neoverse-space-11',
    12: '--neoverse-space-12',
    13: '--neoverse-space-13',
    14: '--neoverse-space-14',
    15: '--neoverse-space-15',
    16: '--neoverse-space-16',
    17: '--neoverse-space-17',
    18: '--neoverse-space-18',
    19: '--neoverse-space-19',
    20: '--neoverse-space-20',
    21: '--neoverse-space-21',
    22: '--neoverse-space-22',
    23: '--neoverse-space-23',
    24: '--neoverse-space-24',
    25: '--neoverse-space-25',
    26: '--neoverse-space-26',
    27: '--neoverse-space-27',
    28: '--neoverse-space-28',
    29: '--neoverse-space-29',
    30: '--neoverse-space-30',
    31: '--neoverse-space-31',
    32: '--neoverse-space-32',
  },
  font: {
    family: {
      sans: '--neoverse-font-family-sans',
      mono: '--neoverse-font-family-mono',
    },
    size: {
      '2xs': '--neoverse-font-size-2xs',
      xs: '--neoverse-font-size-xs',
      sm: '--neoverse-font-size-sm',
      md: '--neoverse-font-size-md',
      lg: '--neoverse-font-size-lg',
      xl: '--neoverse-font-size-xl',
      '2xl': '--neoverse-font-size-2xl',
      '3xl': '--neoverse-font-size-3xl',
      '4xl': '--neoverse-font-size-4xl',
      display: '--neoverse-font-size-display',
    },
    weight: {
      regular: '--neoverse-font-weight-regular',
      medium: '--neoverse-font-weight-medium',
      semibold: '--neoverse-font-weight-semibold',
      bold: '--neoverse-font-weight-bold',
      display: '--neoverse-font-weight-display',
    },
    lineHeight: {
      tight: '--neoverse-line-height-tight',
      snug: '--neoverse-line-height-snug',
      normal: '--neoverse-line-height-normal',
      relaxed: '--neoverse-line-height-relaxed',
    },
    letterSpacing: {
      tight: '--neoverse-letter-spacing-tight',
      normal: '--neoverse-letter-spacing-normal',
      wide: '--neoverse-letter-spacing-wide',
    },
  },
  typography: {
    display: {
      size: '--neoverse-typography-display-size',
      lineHeight: '--neoverse-typography-display-line-height',
      weight: '--neoverse-typography-display-weight',
      letterSpacing: '--neoverse-typography-display-letter-spacing',
    },
    heading: {
      size: '--neoverse-typography-heading-size',
      lineHeight: '--neoverse-typography-heading-line-height',
      weight: '--neoverse-typography-heading-weight',
      letterSpacing: '--neoverse-typography-heading-letter-spacing',
    },
    subtitle: {
      size: '--neoverse-typography-subtitle-size',
      lineHeight: '--neoverse-typography-subtitle-line-height',
      weight: '--neoverse-typography-subtitle-weight',
      letterSpacing: '--neoverse-typography-subtitle-letter-spacing',
    },
    body: {
      size: '--neoverse-typography-body-size',
      lineHeight: '--neoverse-typography-body-line-height',
      weight: '--neoverse-typography-body-weight',
      letterSpacing: '--neoverse-typography-body-letter-spacing',
    },
    label: {
      size: '--neoverse-typography-label-size',
      lineHeight: '--neoverse-typography-label-line-height',
      weight: '--neoverse-typography-label-weight',
      letterSpacing: '--neoverse-typography-label-letter-spacing',
    },
    caption: {
      size: '--neoverse-typography-caption-size',
      lineHeight: '--neoverse-typography-caption-line-height',
      weight: '--neoverse-typography-caption-weight',
      letterSpacing: '--neoverse-typography-caption-letter-spacing',
    },
    code: {
      size: '--neoverse-typography-code-size',
      lineHeight: '--neoverse-typography-code-line-height',
      weight: '--neoverse-typography-code-weight',
      letterSpacing: '--neoverse-typography-code-letter-spacing',
    },
  },
  radius: {
    none: '--neoverse-radius-none',
    xs: '--neoverse-radius-xs',
    sm: '--neoverse-radius-sm',
    md: '--neoverse-radius-md',
    lg: '--neoverse-radius-lg',
    xl: '--neoverse-radius-xl',
    '2xl': '--neoverse-radius-2xl',
    pill: '--neoverse-radius-pill',
    control: '--neoverse-radius-control',
    controlInner: '--neoverse-radius-control-inner',
    card: '--neoverse-radius-card',
    panel: '--neoverse-radius-panel',
  },
  shadow: {
    none: '--neoverse-shadow-none',
    xs: '--neoverse-shadow-xs',
    sm: '--neoverse-shadow-sm',
    md: '--neoverse-shadow-md',
    lg: '--neoverse-shadow-lg',
    xl: '--neoverse-shadow-xl',
    inset: '--neoverse-shadow-inset',
    control: '--neoverse-shadow-control',
    raised: '--neoverse-shadow-raised',
    card: '--neoverse-shadow-card',
    overlay: '--neoverse-shadow-overlay',
    modal: '--neoverse-shadow-modal',
  },
  border: {
    width: {
      none: '--neoverse-border-width-none',
      thin: '--neoverse-border-width-thin',
      strong: '--neoverse-border-width-strong',
    },
    style: {
      solid: '--neoverse-border-style-solid',
    },
  },
  focus: {
    ringColor: '--neoverse-color-focus-ring',
    ringWidth: '--neoverse-focus-ring-width',
    ringOffset: '--neoverse-focus-ring-offset',
    ringOffsetColor: '--neoverse-focus-ring-offset-color',
  },
  material: {
    scale: {
      transparency: {
        opaque: '--neoverse-material-transparency-opaque',
        subtle: '--neoverse-material-transparency-subtle',
        elevated: '--neoverse-material-transparency-elevated',
        immersive: '--neoverse-material-transparency-immersive',
      },
      blur: {
        none: '--neoverse-material-blur-none',
        sm: '--neoverse-material-blur-sm',
        md: '--neoverse-material-blur-md',
        lg: '--neoverse-material-blur-lg',
      },
      saturation: {
        normal: '--neoverse-material-saturation-normal',
        subtle: '--neoverse-material-saturation-subtle',
        elevated: '--neoverse-material-saturation-elevated',
        immersive: '--neoverse-material-saturation-immersive',
      },
      filter: {
        subtle: '--neoverse-material-filter-subtle',
        elevated: '--neoverse-material-filter-elevated',
        immersive: '--neoverse-material-filter-immersive',
      },
      edgeFilter: {
        subtle: '--neoverse-material-edge-filter-subtle',
        elevated: '--neoverse-material-edge-filter-elevated',
        immersive: '--neoverse-material-edge-filter-immersive',
      },
      tint: {
        subtle: '--neoverse-material-tint-subtle',
        elevated: '--neoverse-material-tint-elevated',
        immersive: '--neoverse-material-tint-immersive',
      },
      edgeHighlight: {
        none: '--neoverse-material-edge-highlight-none',
        subtle: '--neoverse-material-edge-highlight-subtle',
        elevated: '--neoverse-material-edge-highlight-elevated',
        immersive: '--neoverse-material-edge-highlight-immersive',
      },
      innerGlow: {
        subtle: '--neoverse-material-inner-glow-subtle',
        elevated: '--neoverse-material-inner-glow-elevated',
        immersive: '--neoverse-material-inner-glow-immersive',
      },
      seamGlow: {
        subtle: '--neoverse-material-seam-glow-subtle',
        elevated: '--neoverse-material-seam-glow-elevated',
        immersive: '--neoverse-material-seam-glow-immersive',
      },
      bloom: {
        subtle: '--neoverse-material-bloom-subtle',
        elevated: '--neoverse-material-bloom-elevated',
        immersive: '--neoverse-material-bloom-immersive',
      },
      edgeRefractionOpacity: {
        subtle: '--neoverse-material-edge-refraction-opacity-subtle',
        elevated: '--neoverse-material-edge-refraction-opacity-elevated',
        immersive: '--neoverse-material-edge-refraction-opacity-immersive',
      },
      edgeRefractionWidth: {
        subtle: '--neoverse-material-edge-refraction-width-subtle',
        elevated: '--neoverse-material-edge-refraction-width-elevated',
        immersive: '--neoverse-material-edge-refraction-width-immersive',
      },
      edgeRefractionSoftness: {
        subtle: '--neoverse-material-edge-refraction-softness-subtle',
        elevated: '--neoverse-material-edge-refraction-softness-elevated',
        immersive: '--neoverse-material-edge-refraction-softness-immersive',
      },
      edgeRefractionCarrier: {
        subtle: '--neoverse-material-edge-refraction-carrier-subtle',
        elevated: '--neoverse-material-edge-refraction-carrier-elevated',
        immersive: '--neoverse-material-edge-refraction-carrier-immersive',
      },
      refractionGradient: {
        none: '--neoverse-material-refraction-gradient-none',
        subtle: '--neoverse-material-refraction-gradient-subtle',
        immersive: '--neoverse-material-refraction-gradient-immersive',
      },
    },
    surface: {
      solid: {
        background: '--neoverse-material-surface-solid-background',
        backgroundFallback: '--neoverse-material-surface-solid-background-fallback',
        transparency: '--neoverse-material-surface-solid-transparency',
        blur: '--neoverse-material-surface-solid-blur',
        saturation: '--neoverse-material-surface-solid-saturation',
        border: '--neoverse-material-surface-solid-border',
        borderWidth: '--neoverse-material-surface-solid-border-width',
        edgeHighlight: '--neoverse-material-surface-solid-edge-highlight',
        shadow: '--neoverse-material-surface-solid-shadow',
        refractionGradient: '--neoverse-material-surface-solid-refraction-gradient',
      },
      subtle: {
        background: '--neoverse-material-surface-subtle-background',
        backgroundFallback: '--neoverse-material-surface-subtle-background-fallback',
        transparency: '--neoverse-material-surface-subtle-transparency',
        blur: '--neoverse-material-surface-subtle-blur',
        saturation: '--neoverse-material-surface-subtle-saturation',
        border: '--neoverse-material-surface-subtle-border',
        borderWidth: '--neoverse-material-surface-subtle-border-width',
        edgeHighlight: '--neoverse-material-surface-subtle-edge-highlight',
        shadow: '--neoverse-material-surface-subtle-shadow',
        refractionGradient: '--neoverse-material-surface-subtle-refraction-gradient',
      },
      elevated: {
        background: '--neoverse-material-surface-elevated-background',
        backgroundFallback: '--neoverse-material-surface-elevated-background-fallback',
        transparency: '--neoverse-material-surface-elevated-transparency',
        blur: '--neoverse-material-surface-elevated-blur',
        saturation: '--neoverse-material-surface-elevated-saturation',
        border: '--neoverse-material-surface-elevated-border',
        borderWidth: '--neoverse-material-surface-elevated-border-width',
        edgeHighlight: '--neoverse-material-surface-elevated-edge-highlight',
        shadow: '--neoverse-material-surface-elevated-shadow',
        refractionGradient: '--neoverse-material-surface-elevated-refraction-gradient',
      },
    },
    glass: {
      subtle: {
        background: '--neoverse-material-glass-subtle-background',
        backgroundFallback: '--neoverse-material-glass-subtle-background-fallback',
        tint: '--neoverse-material-glass-subtle-tint',
        transparency: '--neoverse-material-glass-subtle-transparency',
        blur: '--neoverse-material-glass-subtle-blur',
        saturation: '--neoverse-material-glass-subtle-saturation',
        filter: '--neoverse-material-glass-subtle-filter',
        edgeFilter: '--neoverse-material-glass-subtle-edge-filter',
        border: '--neoverse-material-glass-subtle-border',
        borderWidth: '--neoverse-material-glass-subtle-border-width',
        edgeRefractionOpacity: '--neoverse-material-glass-subtle-edge-refraction-opacity',
        edgeRefractionWidth: '--neoverse-material-glass-subtle-edge-refraction-width',
        edgeRefractionSoftness: '--neoverse-material-glass-subtle-edge-refraction-softness',
        edgeRefractionCarrier: '--neoverse-material-glass-subtle-edge-refraction-carrier',
        edgeHighlight: '--neoverse-material-glass-subtle-edge-highlight',
        innerGlow: '--neoverse-material-glass-subtle-inner-glow',
        seamGlow: '--neoverse-material-glass-subtle-seam-glow',
        bloom: '--neoverse-material-glass-subtle-bloom',
        shadow: '--neoverse-material-glass-subtle-shadow',
        refractionGradient: '--neoverse-material-glass-subtle-refraction-gradient',
      },
      elevated: {
        background: '--neoverse-material-glass-elevated-background',
        backgroundFallback: '--neoverse-material-glass-elevated-background-fallback',
        tint: '--neoverse-material-glass-elevated-tint',
        transparency: '--neoverse-material-glass-elevated-transparency',
        blur: '--neoverse-material-glass-elevated-blur',
        saturation: '--neoverse-material-glass-elevated-saturation',
        filter: '--neoverse-material-glass-elevated-filter',
        edgeFilter: '--neoverse-material-glass-elevated-edge-filter',
        border: '--neoverse-material-glass-elevated-border',
        borderWidth: '--neoverse-material-glass-elevated-border-width',
        edgeRefractionOpacity: '--neoverse-material-glass-elevated-edge-refraction-opacity',
        edgeRefractionWidth: '--neoverse-material-glass-elevated-edge-refraction-width',
        edgeRefractionSoftness: '--neoverse-material-glass-elevated-edge-refraction-softness',
        edgeRefractionCarrier: '--neoverse-material-glass-elevated-edge-refraction-carrier',
        edgeHighlight: '--neoverse-material-glass-elevated-edge-highlight',
        innerGlow: '--neoverse-material-glass-elevated-inner-glow',
        seamGlow: '--neoverse-material-glass-elevated-seam-glow',
        bloom: '--neoverse-material-glass-elevated-bloom',
        shadow: '--neoverse-material-glass-elevated-shadow',
        refractionGradient: '--neoverse-material-glass-elevated-refraction-gradient',
      },
      immersive: {
        background: '--neoverse-material-glass-immersive-background',
        backgroundFallback: '--neoverse-material-glass-immersive-background-fallback',
        tint: '--neoverse-material-glass-immersive-tint',
        transparency: '--neoverse-material-glass-immersive-transparency',
        blur: '--neoverse-material-glass-immersive-blur',
        saturation: '--neoverse-material-glass-immersive-saturation',
        filter: '--neoverse-material-glass-immersive-filter',
        edgeFilter: '--neoverse-material-glass-immersive-edge-filter',
        border: '--neoverse-material-glass-immersive-border',
        borderWidth: '--neoverse-material-glass-immersive-border-width',
        edgeRefractionOpacity: '--neoverse-material-glass-immersive-edge-refraction-opacity',
        edgeRefractionWidth: '--neoverse-material-glass-immersive-edge-refraction-width',
        edgeRefractionSoftness: '--neoverse-material-glass-immersive-edge-refraction-softness',
        edgeRefractionCarrier: '--neoverse-material-glass-immersive-edge-refraction-carrier',
        edgeHighlight: '--neoverse-material-glass-immersive-edge-highlight',
        innerGlow: '--neoverse-material-glass-immersive-inner-glow',
        seamGlow: '--neoverse-material-glass-immersive-seam-glow',
        bloom: '--neoverse-material-glass-immersive-bloom',
        shadow: '--neoverse-material-glass-immersive-shadow',
        refractionGradient: '--neoverse-material-glass-immersive-refraction-gradient',
      },
    },
  },
  motion: {
    duration: {
      fast: '--neoverse-motion-duration-fast',
      standard: '--neoverse-motion-duration-standard',
      expressive: '--neoverse-motion-duration-expressive',
    },
    easing: {
      linear: '--neoverse-motion-easing-linear',
      standard: '--neoverse-motion-easing-standard',
      emphasized: '--neoverse-motion-easing-emphasized',
    },
    spatialDistance: '--neoverse-motion-spatial-distance',
  },
  layout: {
    container: {
      sm: '--neoverse-layout-container-sm',
      md: '--neoverse-layout-container-md',
      lg: '--neoverse-layout-container-lg',
      xl: '--neoverse-layout-container-xl',
      '2xl': '--neoverse-layout-container-2xl',
    },
    gutter: {
      inline: '--neoverse-layout-gutter-inline',
      block: '--neoverse-layout-gutter-block',
    },
    gridGap: '--neoverse-layout-grid-gap',
    layer: {
      base: '--neoverse-layout-layer-base',
      raised: '--neoverse-layout-layer-raised',
      sticky: '--neoverse-layout-layer-sticky',
      overlay: '--neoverse-layout-layer-overlay',
      modal: '--neoverse-layout-layer-modal',
      toast: '--neoverse-layout-layer-toast',
    },
  },
} as const;

export const layoutBreakpoints = {
  sm: 640,
  md: 768,
  lg: 1024,
  xl: 1280,
  '2xl': 1536,
} as const;

export type CssVariables = typeof cssVariables;
export type ColorToken = keyof CssVariables['color'];
export type ColorPrimitiveFamily = keyof CssVariables['color']['primitive'];
export type SpaceToken = keyof CssVariables['space'];
export type FontFamilyToken = keyof CssVariables['font']['family'];
export type FontSizeToken = keyof CssVariables['font']['size'];
export type FontWeightToken = keyof CssVariables['font']['weight'];
export type LineHeightToken = keyof CssVariables['font']['lineHeight'];
export type LetterSpacingToken = keyof CssVariables['font']['letterSpacing'];
export type TypographyRole = keyof CssVariables['typography'];
export type RadiusToken = keyof CssVariables['radius'];
export type ShadowToken = keyof CssVariables['shadow'];
export type FocusToken = keyof CssVariables['focus'];
export type MaterialTransparencyToken = keyof CssVariables['material']['scale']['transparency'];
export type MaterialBlurToken = keyof CssVariables['material']['scale']['blur'];
export type MaterialSaturationToken = keyof CssVariables['material']['scale']['saturation'];
export type MaterialFilterToken = keyof CssVariables['material']['scale']['filter'];
export type MaterialEdgeFilterToken = keyof CssVariables['material']['scale']['edgeFilter'];
export type MaterialTintToken = keyof CssVariables['material']['scale']['tint'];
export type MaterialEdgeHighlightToken = keyof CssVariables['material']['scale']['edgeHighlight'];
export type MaterialInnerGlowToken = keyof CssVariables['material']['scale']['innerGlow'];
export type MaterialSeamGlowToken = keyof CssVariables['material']['scale']['seamGlow'];
export type MaterialBloomToken = keyof CssVariables['material']['scale']['bloom'];
export type MaterialEdgeRefractionOpacityToken =
  keyof CssVariables['material']['scale']['edgeRefractionOpacity'];
export type MaterialEdgeRefractionWidthToken =
  keyof CssVariables['material']['scale']['edgeRefractionWidth'];
export type MaterialEdgeRefractionSoftnessToken =
  keyof CssVariables['material']['scale']['edgeRefractionSoftness'];
export type MaterialRefractionGradientToken =
  keyof CssVariables['material']['scale']['refractionGradient'];
export type MaterialSurfaceToken = keyof CssVariables['material']['surface'];
export type MaterialGlassToken = keyof CssVariables['material']['glass'];
export type MotionToken = keyof CssVariables['motion'];
export type MotionDurationToken = keyof CssVariables['motion']['duration'];
export type MotionEasingToken = keyof CssVariables['motion']['easing'];
export type BorderWidthToken = keyof CssVariables['border']['width'];
export type LayoutContainerToken = keyof CssVariables['layout']['container'];
export type LayoutBreakpoint = keyof typeof layoutBreakpoints;
